# Generated by Django 3.1.1 on 2021-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=100)),
                ('instructor', models.CharField(choices=[('SPC Kalinchenko', 'SPC Kalinchenko'), ('PV2 Oliver', 'PV2 Oliver'), ('SPC Skipwith', 'SPC Skipwith'), ('SGT Dean', 'SGT Dean')], max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
