# Generated by Django 3.0.7 on 2021-02-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_progress',
            name='management_notices',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work_progress',
            name='rsearch',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work_progress',
            name='tl',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
