# Generated by Django 3.0.7 on 2021-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210213_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_progress',
            name='customers',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='cycles',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='management_notices',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='pay_inq',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='recycles',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='rejects',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='rsearch',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_progress',
            name='tl',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
