# Generated by Django 3.0.7 on 2021-02-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210214_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_progress',
            name='cycles',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
