# Generated by Django 3.0.7 on 2021-02-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210214_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
