# Generated by Django 3.0.7 on 2021-02-15 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Appointment',
        ),
        migrations.AlterField(
            model_name='pt',
            name='instructor',
            field=models.CharField(choices=[('Kalinchenko', 'Kalinchenko'), ('Oliver', 'Oliver'), ('Dean', 'Dean'), ('Skipwith', 'Skipwith')], max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=3, null=True)),
                ('hight', models.CharField(blank=True, max_length=3, null=True)),
                ('weight', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
