# Generated by Django 3.0.7 on 2021-02-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210215_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hight',
            new_name='height',
        ),
    ]
