# Generated by Django 3.0.7 on 2021-02-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210215_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
