# Generated by Django 3.0.7 on 2021-02-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210221_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='created_by',
        ),
    ]
