# Generated by Django 3.1.1 on 2021-02-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210221_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='instructor',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
